# Generated by Django 5.1.6 on 2026-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CotizacionHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehiculo", models.CharField(max_length=120)),
                ("cif", models.DecimalField(decimal_places=2, max_digits=12)),
                ("impuestos", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("margen", models.IntegerField(default=30)),
                ("venta", models.DecimalField(decimal_places=2, max_digits=12)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Embarque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ms1_importacion_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("codigo", models.CharField(max_length=32)),
                ("vehiculo", models.CharField(max_length=120)),
                (
                    "referencia",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("origen", models.CharField(blank=True, default="", max_length=80)),
                ("destino", models.CharField(blank=True, default="", max_length=80)),
                ("naviera", models.CharField(blank=True, default="", max_length=80)),
                ("etapa_actual", models.CharField(default="COMPRADO", max_length=24)),
                ("fecha_estimada", models.DateField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
